// ─── AI GROUP STAGE PREDICTIONS ──────────────────────────────────────────────
// Generated by Claude Sonnet 4.6 — May 2026
// Fields: h (home goals), a (away goals), r (short reason),
//         insight (2-3 sentence analysis), key (key factor), confidence

const GROUP_AI_PREDICTIONS = {

  // ── GROUP A ──────────────────────────────────────────────────────────────────
  "Mexico||South Africa": {
    h:2, a:0, confidence:"High",
    r:"Mexico dominant at home vs a South Africa side ranked 61st",
    insight:"Mexico play all group games on home soil with passionate support behind them. South Africa were docked World Cup qualifying points for fielding an ineligible player and are considered the weakest team in Group A. El Tri ranked 15th in the world — a 20+ place gap tells the story.",
    key:"Home advantage and quality gulf",
  },
  "South Korea||Czechia": {
    h:1, a:1, confidence:"Medium",
    r:"RotoWire projects both teams nearly identically — genuine 50/50",
    insight:"RotoWire gives both teams 4.2 projected points across the group stage — the closest projection of any group matchup. South Korea sailed through Asian qualifying undefeated but this is a massive step up. Czechia have the structure to frustrate; Son Heung-min is the wild card.",
    key:"Son Heung-min's ability to break the deadlock",
  },
  "Czechia||South Africa": {
    h:2, a:0, confidence:"High",
    r:"European quality too strong for South Africa who struggled in qualifying",
    insight:"Czechia's Bundesliga and Premier League-based squad are well-organised and experienced at international level. South Africa's qualifying form was poor and they've never progressed past the group stage. A comfortable Czech win sets up their race with South Korea for second.",
    key:"Czechia's defensive organisation vs South Africa's limited attack",
  },
  "Mexico||South Korea": {
    h:2, a:1, confidence:"Medium",
    r:"Mexico's home advantage edges a resilient South Korea",
    insight:"This is the real Group A decider for top spot. South Korea are unbeaten in Asian qualifying and Son is at peak powers. Mexico haven't beaten a top opponent recently but 80,000 fans at Estadio Azteca changes the dynamic completely. Expect a competitive game decided late.",
    key:"Estadio Azteca atmosphere and Son Heung-min's impact",
  },
  "Czechia||Mexico": {
    h:0, a:2, confidence:"Medium",
    r:"Mexico secure top spot — Czechia may rotate if already qualified",
    insight:"By matchday 3 Mexico likely need just a point. Czechia, potentially already through, may rotate. Even at full strength Mexico's home advantage is decisive — CBS Sports backs El Tri to reach the R16 at minimum.",
    key:"Rotation risk and Mexico's attacking depth",
  },
  "South Africa||South Korea": {
    h:0, a:2, confidence:"High",
    r:"Son Heung-min the difference as South Korea cruise to second place",
    insight:"South Korea need this win to advance and Son will be the difference. South Africa have shown nothing to suggest they can trouble top opposition. Son's pace and finishing ability gives South Korea a weapon South Africa simply can't handle.",
    key:"Son Heung-min vs South Africa's defensive frailty",
  },

  // ── GROUP B ──────────────────────────────────────────────────────────────────
  "Canada||Bosnia-Herzegovina": {
    h:2, a:1, confidence:"Medium",
    r:"Jonathan David and Alphonso Davies give Canada the edge at home",
    insight:"Canada's third World Cup but their first with genuine quality throughout the squad. David is one of the most prolific forwards in Europe and Davies brings pace and danger from left back. Bosnia have quality in midfield but lack firepower. Home crowd in Toronto will be electric.",
    key:"Jonathan David's finishing quality",
  },
  "Qatar||Switzerland": {
    h:0, a:3, confidence:"High",
    r:"Switzerland far superior — Qatar's group exit form continues",
    insight:"Qatar became the first hosts to exit in the group stage in 2022 and this looks even harder. Switzerland are ranked 17th in the world — a full 10 places above Canada in this group. Granit Xhaka runs their midfield authoritatively and Qatar have no answer for European pressing.",
    key:"Switzerland's pressing intensity vs Qatar's passive style",
  },
  "Switzerland||Bosnia-Herzegovina": {
    h:2, a:0, confidence:"High",
    r:"Swiss defensive solidity and tournament experience decisive",
    insight:"Switzerland are the model of tournament consistency — well-organised, difficult to beat, and technically excellent. Bosnia's strength is in their creative midfield but Switzerland's backline is one of the best in Europe at shutting down space. Shaqiri provides the spark to create the goals.",
    key:"Switzerland's defensive structure",
  },
  "Canada||Qatar": {
    h:3, a:0, confidence:"High",
    r:"Canada need goals — Qatar have no answers for North American hosts",
    insight:"Qatar are the weakest team at the tournament and Canada will go for the jugular knowing GD could matter. Jonathan David could get a hat-trick here. Canada's home crowd make this even more one-sided — expect this to be one of the biggest wins of the group stage.",
    key:"Goal difference — Canada go for as many as possible",
  },
  "Switzerland||Canada": {
    h:1, a:1, confidence:"Medium",
    r:"Both sides likely cautious knowing a draw probably advances both",
    insight:"If Switzerland and Canada are already qualified, this could be a fascinating chess match between two well-coached sides who know the mathematics. Xhaka vs Davies is the tactical battle. The team that needs a win will be more aggressive — but expect conservative football.",
    key:"Group table mathematics at kick-off",
  },
  "Bosnia-Herzegovina||Qatar": {
    h:2, a:0, confidence:"High",
    r:"Bosnia fight for pride — Qatar offer little resistance",
    insight:"Bosnia will be desperate for a win after likely losing their first two. Qatar, almost certainly eliminated, have nothing to play for. Dzeko's experience and Bosnia's attacking quality should be far too much for a Qatar side whose tournament adventure ends here.",
    key:"Bosnia's desperation vs Qatar's lack of motivation",
  },

  // ── GROUP C ──────────────────────────────────────────────────────────────────
  "Brazil||Morocco": {
    h:2, a:1, confidence:"Medium",
    r:"Vinicius Jr. and Rodrygo too dangerous even for Morocco's famous block",
    insight:"Morocco's 2022 semi-final run was built on an impenetrable defence, but Brazil's attack is on another level. Vinicius Jr. terrorises defenders with his pace and directness. Brazil are ranked 5th globally and despite inconsistent recent form, a group opener vs Morocco brings out their best.",
    key:"Vinicius Jr.'s pace vs Morocco's defensive discipline",
  },
  "Haiti||Scotland": {
    h:0, a:2, confidence:"High",
    r:"Scotland handle Haiti's debut comfortably — Robertson and McGinn influential",
    insight:"Haiti's first World Cup is an incredible story but the quality gap is stark. Scotland have Premier League and Championship quality throughout and Andy Robertson's bombing runs from left back will cause Haiti serious problems. Goals from set pieces — Scotland's specialty — likely.",
    key:"Set piece threat and Robertson's delivery",
  },
  "Scotland||Morocco": {
    h:0, a:1, confidence:"Medium",
    r:"Morocco's tactical discipline and pace edges a limited Scotland attack",
    insight:"Morocco will be the biggest test Scotland face in the group. Hakimi's pace on the right flank is a constant danger and Morocco's defensive block is well-drilled. Scotland will work hard but their attack lacks the creativity to unlock Morocco's shape. A narrow Moroccan win expected.",
    key:"Hakimi's pace vs Scotland's defensive organisation",
  },
  "Brazil||Haiti": {
    h:5, a:0, confidence:"High",
    r:"Brazil score freely — Haiti's first World Cup offers no resistance",
    insight:"This is the most one-sided match of Group C. Brazil will want to run up a big score for goal difference purposes and Haiti simply don't have the quality to stop them. Neymar, Vinicius and Rodrygo will rotate chances — Brazil's squad depth means even their rotation players are world class.",
    key:"Brazil's squad depth vs Haiti's inexperience",
  },
  "Scotland||Brazil": {
    h:0, a:3, confidence:"High",
    r:"Brazil's attacking quality in a different class — Scotland outgunned",
    insight:"Scotland will set up defensively and make it difficult for 60 minutes, but Brazil's quality always tells. The pressure of needing to secure qualification will keep Scotland's ambitions in check. Brazil will use their superior fitness and technical quality to find the breakthrough eventually.",
    key:"Brazil's eventual quality over Scottish resilience",
  },
  "Morocco||Haiti": {
    h:3, a:0, confidence:"High",
    r:"Morocco secure second place comfortably against outclassed Haiti",
    insight:"Morocco will be fully focused on securing second place and a decent group position. Haiti's defensive organisation is their only tool but it won't be enough against Morocco's pace and creativity. En-Nesyri's aerial threat from set pieces adds another dimension Morocco can exploit.",
    key:"Morocco's pace and set piece threat",
  },

  // ── GROUP D ──────────────────────────────────────────────────────────────────
  "USA||Paraguay": {
    h:2, a:1, confidence:"High",
    r:"USMNT strong at home — Pulisic and Reyna the difference",
    insight:"The USMNT's first World Cup match on home soil in 32 years at MetLife Stadium will be electric. Pulisic brings experience from Chelsea, Reyna is finally injury-free, and Folarin Balogun offers a clinical finishing option. Paraguay are competitive but the home atmosphere gives USA a significant edge.",
    key:"MetLife Stadium atmosphere and Pulisic's leadership",
  },
  "Australia||Turkey": {
    h:1, a:1, confidence:"Low",
    r:"Evenly matched sides — Turkey's Bundesliga quality vs Australia's Socceroos spirit",
    insight:"This is the hardest match in Group D to predict. Turkey have genuine Bundesliga talent but inconsistency is their trademark. Australia's spirit and pressing can trouble anyone — they reached the 2022 quarter-finals. A genuine 50/50 with the draw the most likely single outcome.",
    key:"Whoever controls the midfield battle",
  },
  "USA||Australia": {
    h:2, a:1, confidence:"Medium",
    r:"USA home advantage and depth edges a spirited Australia side",
    insight:"Australia's Socceroos are never easy opponents — their pressing game suits a World Cup tempo. But USA's depth, physicality and home crowd advantage should be decisive. Balogun vs the Australian defence is the key matchup. Australia will compete hard but likely fall short.",
    key:"USA's home advantage and physical depth",
  },
  "Turkey||Paraguay": {
    h:2, a:1, confidence:"Medium",
    r:"Turkey's European quality sees off Paraguay in a competitive game",
    insight:"Turkey have genuine Bundesliga and Serie A quality but are inconsistent. Paraguay play a physical South American style that can disrupt European opponents. Turkey's extra individual quality in the final third should be the difference in what promises to be a combative game.",
    key:"Turkey's individual quality in the final third",
  },
  "Turkey||USA": {
    h:1, a:2, confidence:"Medium",
    r:"USA edge it at home in a crucial qualification match",
    insight:"By matchday 3 this could be winner-takes-all for the runners-up spot. USA's home advantage is amplified when they need it most — the crowd at a major US city stadium will be extraordinary. Turkey will make it hard but USA's depth and experience of big occasions edges it.",
    key:"USA's home support in a must-win scenario",
  },
  "Paraguay||Australia": {
    h:1, a:1, confidence:"Low",
    r:"Neither side can afford to lose — cautious draw likely",
    insight:"Both teams will likely need a win to advance by matchday 3, making this an intriguing tactical battle. Paraguay's physicality vs Australia's pressing game is a fascinating clash of styles. The team that scores first will have a huge advantage — but a draw benefits both if Turkey and USA draw too.",
    key:"Group table mathematics at kick-off",
  },

  // ── GROUP E ──────────────────────────────────────────────────────────────────
  "Germany||Curacao": {
    h:5, a:0, confidence:"High",
    r:"Germany make a statement after 2022 failure — Curacao hopelessly outmatched",
    insight:"Germany crashed out in the group stage in 2018 and 2022 — this squad is desperate to restore national pride. A new generation led by Wirtz, Musiala and Havertz is genuinely exciting. Curacao are simply not in the same league. Germany need a big win for GD and they'll get it.",
    key:"Germany's redemption motivation and Wirtz/Musiala quality",
  },
  "Ivory Coast||Ecuador": {
    h:1, a:1, confidence:"Low",
    r:"Ivory Coast pace vs Ecuador organisation — competitive and evenly matched",
    insight:"Group E's most unpredictable match. Ivory Coast have electric pace in attack with players from Ligue 1 and the Premier League, but Ecuador's young squad is well-organised and disciplined. Neither team is a pushover and neither can afford to lose to Germany. A draw suits both.",
    key:"Whether Ivory Coast's pace can unlock Ecuador's structure",
  },
  "Germany||Ivory Coast": {
    h:2, a:1, confidence:"Medium",
    r:"Germany win but Ivory Coast's pace causes real problems",
    insight:"Ivory Coast will press Germany high and their wingers have the pace to trouble even the best defences. Germany's superior depth and technical quality should win out but this won't be comfortable. Expect Germany to go behind at some point — their response to adversity is the key test.",
    key:"Germany's response when pressed by Ivory Coast's pace",
  },
  "Ecuador||Curacao": {
    h:4, a:0, confidence:"High",
    r:"Ecuador maximise GD — Curacao are ideal opponents for big score",
    insight:"Ecuador need to keep pace with Germany in the goal difference stakes. Curacao are essentially a CONCACAF side competing at the very top level for the first time. Ecuador's young squad will see this as a chance to score freely and build momentum. Valencia leads the charge.",
    key:"Ecuador's GD ambitions — they'll go for maximum goals",
  },
  "Curacao||Ivory Coast": {
    h:0, a:3, confidence:"High",
    r:"Ivory Coast's quality far too much for Curacao — comfortable win",
    insight:"Curacao are making their World Cup debut and the step up in quality will be enormous. Ivory Coast's pace and creativity will overwhelm their defensive shape. This is Ivory Coast's chance to build goal difference and they'll take it — their wingers will run riot.",
    key:"Ivory Coast's pace and power against a limited Curacao",
  },
  "Ecuador||Germany": {
    h:0, a:2, confidence:"High",
    r:"Germany secure top spot — Ecuador give it a go but are outclassed",
    insight:"If both sides are already qualified, Germany may rotate but still have the quality to win. Ecuador's best chance is early — if they can take the lead they might park the bus. But Germany's technical quality and passing will eventually find a way through.",
    key:"Germany's passing quality vs Ecuador's defensive block",
  },

  // ── GROUP F ──────────────────────────────────────────────────────────────────
  "Netherlands||Japan": {
    h:2, a:1, confidence:"Medium",
    r:"Netherlands edge it but Japan's giant-killing form makes this nervy — de Jong injury concern",
    insight:"Japan beat Germany and Spain in 2022 — nobody takes them lightly. Frenkie de Jong's hamstring injury adds uncertainty for the Dutch midfield. RotoWire gives Japan 58% qualification probability — second highest in Group F. Gakpo and Depay have the individual quality but Japan's pressing is relentless.",
    key:"Frenkie de Jong's fitness and Japan's pressing intensity",
  },
  "Sweden||Tunisia": {
    h:2, a:0, confidence:"High",
    r:"Alexander Isak's pace and quality decisive — Tunisia limited going forward",
    insight:"Alexander Isak is one of the most complete centre-forwards in world football right now — powerful, technically excellent and clinical. Tunisia set up defensively but their attack offers little. Sweden's Bundesliga and Premier League quality throughout should be too much in a straightforward win.",
    key:"Alexander Isak's individual quality",
  },
  "Netherlands||Sweden": {
    h:2, a:1, confidence:"Medium",
    r:"Gakpo vs Isak is the headline battle — Netherlands' depth decides it",
    insight:"This is Group F's best match. Gakpo and Isak are both elite strikers and the tactical battle between two well-organised sides will be fascinating. Netherlands have the edge in midfield quality and depth but Sweden are dangerous on the counter. A goal from a set piece could decide it.",
    key:"Midfield battle — Gakpo vs Isak one-on-one duels",
  },
  "Tunisia||Japan": {
    h:0, a:2, confidence:"High",
    r:"Japan's pressing overwhelming for Tunisia's defensive setup",
    insight:"Japan's high press and quick transitions are perfectly suited to exposing Tunisia's relatively passive defensive shape. Kubo and Ito's pace on the wings will cause Tunisia's fullbacks serious problems. Japan showed in 2022 they can beat anyone — Tunisia don't have the technical quality to match them.",
    key:"Japan's high press and transition speed",
  },
  "Japan||Sweden": {
    h:1, a:2, confidence:"Medium",
    r:"Sweden's aerial threat and Isak's movement gives Japan real problems",
    insight:"Japan's defence struggles against aerial threats and Sweden will exploit set pieces and Isak's movement. Japan will press high and create chances but Sweden's physicality makes them hard to break down in open play. A close game decided by Isak's individual quality.",
    key:"Isak's aerial and physical dominance vs Japan's high line",
  },
  "Tunisia||Netherlands": {
    h:0, a:3, confidence:"High",
    r:"Netherlands top the group — Tunisia have little to offer at this level",
    insight:"Netherlands are comfortably the best team in Group F and Tunisia the weakest. By matchday 3 Netherlands will want to secure top spot with a convincing win for morale heading into the knockout stage. Tunisia's defensive organisation buys them time but not points.",
    key:"Netherlands' technical quality overwhelming Tunisia",
  },

  // ── GROUP G ──────────────────────────────────────────────────────────────────
  "Belgium||Egypt": {
    h:3, a:0, confidence:"High",
    r:"De Bruyne leads Belgium — third highest projected goal total of all 48 teams",
    insight:"RotoWire projects Belgium as one of the tournament's most attacking sides with 6.3 projected goals in the group stage — third highest of all 48 teams. De Bruyne's creativity and Lukaku's finishing make them devastating. Egypt have Salah but their supporting cast can't match Belgium's depth.",
    key:"De Bruyne's creativity and Belgium's attacking depth",
  },
  "Iran||New Zealand": {
    h:2, a:0, confidence:"High",
    r:"Iran's tournament experience decisive against New Zealand's debut",
    insight:"New Zealand have rarely qualified for World Cups and the quality gap is significant. Iran have genuine experience from their 2018 and 2022 campaigns and their defensive organisation is formidable. Taremi is a clinical striker at club level — New Zealand's defence will struggle.",
    key:"Taremi's finishing vs New Zealand's inexperience",
  },
  "Belgium||Iran": {
    h:2, a:0, confidence:"High",
    r:"Belgium's press breaks Iran's defensive block — Lukaku the difference",
    insight:"Iran set up in a low defensive block which can frustrate teams, but Belgium's movement and De Bruyne's passing range creates gaps even in deep defences. Lukaku's physicality is a nightmare for Iran's defensive leaders. Belgium's 65% group win probability reflects their dominance.",
    key:"Belgium's ability to unlock a deep defensive block",
  },
  "New Zealand||Egypt": {
    h:0, a:2, confidence:"High",
    r:"Salah makes the difference — Egypt's quality too much for New Zealand",
    insight:"Even at 33, Salah is still one of world football's most effective players. New Zealand simply don't have the technical quality to handle him when he's on the ball. Egypt's supporting cast have improved significantly and this is a must-win for their advancement hopes.",
    key:"Mohamed Salah's individual quality",
  },
  "Egypt||Iran": {
    h:1, a:1, confidence:"Low",
    r:"Neither side can afford to lose — tactical and tense, draw most likely",
    insight:"Both teams will likely need something from this game. Iran's defensive organisation makes them difficult to beat and Egypt, while having Salah, can struggle to create against a deep block. The political backdrop between these nations adds extra tension. Expect a cautious, tight game.",
    key:"Iran's defensive discipline vs Salah's individual brilliance",
  },
  "New Zealand||Belgium": {
    h:0, a:4, confidence:"High",
    r:"Belgium's dominance on full show — New Zealand overwhelmed",
    insight:"Belgium will want to top the group and a big win here helps goal difference. New Zealand have no answer for De Bruyne's range of passing and Lukaku's movement. Belgium's 65% group win probability is the highest in their group by far — this game shows exactly why.",
    key:"Belgium's attacking quality vs New Zealand's quality gap",
  },

  // ── GROUP H ──────────────────────────────────────────────────────────────────
  "Spain||Cape Verde": {
    h:4, a:0, confidence:"High",
    r:"Spain leads all 48 teams in projected goals — Yamal and Pedri vs Cape Verde",
    insight:"RotoWire projects Spain with nearly 15 goals across the group stage — more than any other team. Lamine Yamal at 18 is already one of the best players in the world, Pedri controls midfield and Morata provides the finishing. Cape Verde's AFCON form won't translate to this level.",
    key:"Lamine Yamal's creativity — Spain's generational talent on display",
  },
  "Saudi Arabia||Uruguay": {
    h:0, a:2, confidence:"High",
    r:"Uruguay's Nunez too powerful for Saudi defence despite their famous 2022 upset",
    insight:"Saudi Arabia's 2022 win over Argentina was one of the great World Cup upsets but Uruguay are a different proposition — organised, physical and with Nunez as a genuine world-class threat. Saudi's defensive block will be tested severely by Uruguay's direct play and Nunez's aerial dominance.",
    key:"Darwin Nunez's physicality and finishing vs Saudi's defence",
  },
  "Spain||Saudi Arabia": {
    h:3, a:0, confidence:"High",
    r:"Spain's possession game and pressing overwhelms Saudi Arabia's defensive shape",
    insight:"Spain's tiki-taka evolution under their current manager suits the modern game. Saudi Arabia cannot live with Spain's ball circulation and pressing triggers — their 2022 high defensive line will be their undoing. Pedri and Gavi in midfield means Spain simply won't lose the ball.",
    key:"Spain's ball circulation vs Saudi's high defensive line",
  },
  "Uruguay||Cape Verde": {
    h:2, a:0, confidence:"High",
    r:"Uruguay's South American quality and Nunez's power decisive",
    insight:"Uruguay are one of the most experienced teams in the tournament and know how to manage group stage pressure. Cape Verde are a spirited AFCON side but the step up to World Cup level is enormous. Nunez's directness and Valverde's engine from midfield should be too much.",
    key:"Nunez's directness and Valverde's midfield control",
  },
  "Cape Verde||Saudi Arabia": {
    h:1, a:1, confidence:"Low",
    r:"Dead rubber — neither team with much to play for, cagey draw",
    insight:"Both teams will likely be eliminated by this point. Pride is the only motivator. Cape Verde will be competitive — they always are — but Saudi Arabia have quality players who won't want to end on a defeat. Expect a low-intensity, cagey match that both sides are happy to draw.",
    key:"Motivation levels of two likely-eliminated sides",
  },
  "Uruguay||Spain": {
    h:1, a:2, confidence:"Medium",
    r:"Group H decider — Spain's technical superiority edges Uruguay's physicality",
    insight:"The match of Group H. Uruguay will make this incredibly hard — their defensive organisation and physical intensity will test even Spain. But Spain's technical quality and passing range eventually tells. Expect Uruguay to score on the counter — this won't be 3-0, it'll be fought for.",
    key:"Spain's technical quality vs Uruguay's defensive intensity",
  },

  // ── GROUP I ──────────────────────────────────────────────────────────────────
  "France||Senegal": {
    h:2, a:1, confidence:"High",
    r:"Mbappe vs Mane headline duel — France +500 tournament favourites have the depth",
    insight:"France are joint second favourites at +500 alongside arguably the most complete squad at the tournament. Mbappe at full pace is unplayable on his day. Mane is still dangerous but Senegal's supporting cast can't match France's depth at every position. Expect Mbappe to be the difference.",
    key:"Kylian Mbappe's pace and finishing against Senegal's defence",
  },
  "Iraq||Norway": {
    h:0, a:3, confidence:"High",
    r:"Haaland gets his warm-up — Iraq hopelessly outmatched against Norway's striker",
    insight:"This is Erling Haaland's stage and Iraq are the unfortunate opponents. Norway's directness and Haaland's movement in behind will cause Iraq's defence serious problems from the first minute. ESPN flags Mbappe vs Haaland as the tournament's marquee matchup — but Haaland needs to get to that game first.",
    key:"Erling Haaland's movement and finishing in space",
  },
  "France||Iraq": {
    h:4, a:0, confidence:"High",
    r:"France rotate but still win heavily — their second string is world class",
    insight:"France's squad depth is extraordinary — their rotation players would walk into most international squads. Dembele, Coman, Thuram off the bench or in the starting XI — it barely matters. Iraq have shown nothing to suggest they can trouble France even at 60% intensity.",
    key:"France's squad depth — rotation players still world class",
  },
  "Norway||Senegal": {
    h:2, a:1, confidence:"Medium",
    r:"Haaland's physicality vs Senegal's defenders — Norway's directness wins it",
    insight:"Senegal's centre-backs will be tested severely by Haaland's movement. Norway play a direct style that suits Haaland perfectly — getting balls in behind for him to chase. Senegal's midfield quality is their strength but Norway's pressing will limit their time on the ball.",
    key:"Erling Haaland against Senegal's centre-back pairing",
  },
  "Norway||France": {
    h:1, a:2, confidence:"Medium",
    r:"Mbappe vs Haaland — the tournament's marquee group match, France edge it",
    insight:"ESPN specifically highlights this as one of the tournament's must-see matches — two of the world's best strikers facing off. France will have more control through the midfield and their defensive depth handles Norway's directness better than vice versa. But Haaland will score — he always does.",
    key:"Midfield control — France's Tchouameni vs Norway's pressing",
  },
  "Senegal||Iraq": {
    h:3, a:0, confidence:"High",
    r:"Senegal quality shines in must-win match — Iraq have no answer",
    insight:"Senegal need this win to have any chance of advancing and Iraq don't have the quality to stop them. Mane leads the line with pace and creativity behind him. This should be one-sided and comfortable — Senegal's AFCON experience gives them the mentality to handle the pressure.",
    key:"Senegal's desperation and AFCON-winning mentality",
  },

  // ── GROUP J ──────────────────────────────────────────────────────────────────
  "Argentina||Algeria": {
    h:3, a:0, confidence:"High",
    r:"Defending champions start with a statement — Messi's final World Cup",
    insight:"Argentina are one of three tournament co-favourites and this group opener is a chance to send a message. Messi at what is almost certainly his final World Cup will be extra motivated. Algeria are a decent AFCON side but the gulf in class is enormous. Di Maria, Alvarez and Messi — devastating.",
    key:"Messi's motivation on his final World Cup stage",
  },
  "Austria||Jordan": {
    h:3, a:0, confidence:"High",
    r:"Austria's Bundesliga quality decisive against Jordan's World Cup debut",
    insight:"Austria have genuine Bundesliga quality throughout — David Alaba's leadership, Arnautovic's finishing, Sabitzer's midfield control. Jordan are making their first World Cup appearance and the quality gap is significant. Austria should cruise through without breaking sweat.",
    key:"Austria's technical quality vs Jordan's inexperience",
  },
  "Argentina||Austria": {
    h:2, a:1, confidence:"High",
    r:"Argentina too good but Austria will make it hard — Arnautovic a genuine threat",
    insight:"Austria won't roll over — they're a well-organised side with a high defensive line and Arnautovic's physical presence causes problems even for world-class defences. But Argentina's attacking trio of Messi, Alvarez and Di Maria is simply on another level. Argentina win but not comfortably.",
    key:"Argentina's creative trio vs Austria's defensive organisation",
  },
  "Jordan||Algeria": {
    h:0, a:2, confidence:"High",
    r:"Algeria's AFCON experience decisive — Jordan's debut limited by squad quality",
    insight:"Algeria are one of Africa's strongest nations historically and their AFCON experience gives them a significant advantage over Jordan. Algeria's pressing style will overwhelm Jordan's relatively limited technical quality. Mahrez, if fit, provides the creative spark that Jordan simply cannot match.",
    key:"Algeria's AFCON experience and Mahrez's creativity",
  },
  "Algeria||Austria": {
    h:1, a:2, confidence:"Medium",
    r:"Austria edge it but Algeria's AFCON form makes this competitive",
    insight:"This could be a fascinating match if both sides are still in contention for second place. Algeria's technical quality from their AFCON squad is underestimated — Belaili and Mahrez can hurt anyone. But Austria's physical intensity and Bundesliga organisation should see them through.",
    key:"Austria's physical intensity vs Algeria's technical quality",
  },
  "Jordan||Argentina": {
    h:0, a:4, confidence:"High",
    r:"Argentina win big — Messi and Alvarez share the goals in a group stage finale",
    insight:"If Argentina are already through, this is their chance to build momentum and goal difference. Jordan showed heart against Algeria but they simply don't have the quality to trouble Argentina. Messi may rest but the depth behind him means a big win is still expected.",
    key:"Argentina's squad depth even with rotation",
  },

  // ── GROUP K ──────────────────────────────────────────────────────────────────
  "Portugal||DR Congo": {
    h:3, a:0, confidence:"High",
    r:"Bruno Fernandes and Bernardo Silva control midfield — DR Congo overwhelmed",
    insight:"Portugal's midfield is one of the best in the tournament — Bruno Fernandes, Bernardo Silva and potentially Vitinha combine creativity, pressing and technical quality. DR Congo's African Cup experience doesn't prepare them for this level. Ronaldo leads the line with typically decisive presence.",
    key:"Portugal's midfield superiority and Ronaldo's finishing",
  },
  "Uzbekistan||Colombia": {
    h:0, a:2, confidence:"High",
    r:"James Rodriguez's class and Colombia's South American quality too much",
    insight:"James Rodriguez at his best is one of the most creative players in world football. Colombia's squad has genuine depth across all positions built on their strong league and European presence. Uzbekistan are making significant strides but are simply outgunned in every department.",
    key:"James Rodriguez's creativity and Colombia's technical depth",
  },
  "Portugal||Uzbekistan": {
    h:4, a:0, confidence:"High",
    r:"Portugal run up a big score — Uzbekistan completely out of their depth",
    insight:"Portugal will want to set a strong goal difference statement early and Uzbekistan are the ideal opponents. Ronaldo hunting for goals, Bruno creating and Bernardo driving from midfield — Portugal's attack is too much for any Central Asian side. Expect Portugal's biggest win of the group.",
    key:"Portugal's goal difference ambitions vs Uzbekistan's quality gap",
  },
  "Colombia||DR Congo": {
    h:2, a:0, confidence:"High",
    r:"Colombia's tactical organisation and technical quality decisive",
    insight:"Colombia's mix of European-based and MLS players gives them a well-rounded squad. DR Congo's strength is their athleticism and direct play but Colombia's midfield control limits the spaces they want to exploit. James Rodriguez pulling the strings is simply too much for DR Congo to handle.",
    key:"Colombia's midfield control vs DR Congo's directness",
  },
  "Colombia||Portugal": {
    h:1, a:2, confidence:"Medium",
    r:"Group K's top match — Portugal's European pedigree edges a competitive Colombia",
    insight:"This is Group K's standout match — two technically excellent sides with genuine star quality. Colombia will press high and James Rodriguez's creativity can hurt anyone. But Portugal's experience of big tournament moments and Ronaldo's big-game mentality gives them a narrow edge.",
    key:"Portugal's tournament experience vs Colombia's pressing intensity",
  },
  "DR Congo||Uzbekistan": {
    h:2, a:0, confidence:"Medium",
    r:"DR Congo's pace and physicality decisive in a group-stage finale for third place",
    insight:"Both sides will likely be eliminated but DR Congo's athleticism and direct play gives them the edge over Uzbekistan's more technical approach. DR Congo's CAF experience at AFCON level is relevant here — they've competed against better opponents than Uzbekistan regularly.",
    key:"DR Congo's physical advantage and directness",
  },

  // ── GROUP L ──────────────────────────────────────────────────────────────────
  "England||Croatia": {
    h:2, a:1, confidence:"High",
    r:"Bellingham leads England's revenge for 2018 — stronger squad and a point to prove",
    insight:"England's 2018 semi-final loss to Croatia is burned into their consciousness. This squad is significantly stronger — Bellingham, Saka, Foden and Rice give them world-class quality in every area. Croatia's Modric is ageing but remains brilliant. England win but not comfortably early on.",
    key:"Jude Bellingham's quality in the final third vs Modric's experience",
  },
  "Ghana||Panama": {
    h:2, a:0, confidence:"High",
    r:"Ghana's Premier League talent too much for Panama's physical but limited squad",
    insight:"Ghana have Premier League and Bundesliga quality across their squad — Kudus, Partey, Ayew. Panama play a very physical, direct style that can frustrate technical teams but Ghana have the individual quality to find ways through. A comfortable Ghana win sets up their run at advancement.",
    key:"Kudus and Partey's individual quality vs Panama's physicality",
  },
  "England||Ghana": {
    h:3, a:0, confidence:"High",
    r:"England's depth dominant — Saka and Bellingham the stars, Ghana can't live with it",
    insight:"England's second group game is a chance to confirm qualification. Ghana are a decent team but England's depth at every position is overwhelming at this level. Saka's creativity from the right wing, Bellingham's movement through midfield — Ghana's defence will be on the back foot all game.",
    key:"England's squad depth and Saka's right-wing creativity",
  },
  "Panama||Croatia": {
    h:0, a:2, confidence:"High",
    r:"Modric orchestrates — Croatia's tournament experience too much for Panama",
    insight:"Croatia's midfield trio of Modric, Kovacic and Brozovic remains one of the best in world football despite their age. Panama's physicality is their weapon but Croatia's passing and movement renders that ineffective. Expect a controlled Croatian performance — they make hard games look simple.",
    key:"Croatia's midfield dominance vs Panama's physical style",
  },
  "Panama||England": {
    h:0, a:4, confidence:"High",
    r:"Echoes of England 6-1 Panama in 2018 — similar result expected with rotation",
    insight:"England hammered Panama 6-1 in 2018 and a similar result is expected even with rotation. England will manage this game professionally — the squad players want to impress Southgate's successor. Panama's physical approach won't trouble England's technical quality at all.",
    key:"England's squad depth overwhelming Panama even with rotation",
  },
  "Croatia||Ghana": {
    h:2, a:1, confidence:"Medium",
    r:"Croatia's big-game experience decisive in a tight group decider",
    insight:"Both sides need to win to have any chance of advancing. Modric's leadership in big moments is Croatia's greatest asset. Ghana will press high and Kudus's pace is a constant danger. A tight, competitive game that Croatia's experience and individual quality edges in the final 20 minutes.",
    key:"Modric's leadership vs Kudus's pace in a winner-takes-all finale",
  },
};

export default GROUP_AI_PREDICTIONS;
