// ─── AI GROUP STAGE PREDICTIONS ──────────────────────────────────────────────
// Generated by Claude Sonnet 4.6 — May 2026
// Based on FIFA rankings, recent form, tournament odds and squad analysis
// Format: { h, a, r (reason), confidence }

const GROUP_AI_PREDICTIONS = {

  // ── GROUP A ──────────────────────────────────────────────────────────────────
  "Mexico||South Africa": { h:2, a:0, r:"Mexico dominant at home, South Africa ranked 61st with poor qualifying form", confidence:"High" },
  "South Korea||Czechia": { h:1, a:1, r:"Evenly matched — South Korea press vs Czechia structure ends level", confidence:"Medium" },
  "Czechia||South Africa": { h:2, a:0, r:"Czechia's European quality too strong for South Africa who struggled in qualifying", confidence:"High" },
  "Mexico||South Korea": { h:2, a:1, r:"Mexico home advantage and attacking depth edges resilient South Korea", confidence:"Medium" },
  "Czechia||Mexico": { h:0, a:2, r:"Mexico secure top spot — Czechia struggle against quality opposition", confidence:"Medium" },
  "South Africa||South Korea": { h:0, a:2, r:"Son Heung-min the difference as South Korea cruise to second place", confidence:"High" },

  // ── GROUP B ──────────────────────────────────────────────────────────────────
  "Canada||Bosnia-Herzegovina": { h:2, a:1, r:"Jonathan David and Alphonso Davies give Canada the edge at home", confidence:"Medium" },
  "Qatar||Switzerland": { h:0, a:3, r:"Switzerland far superior — Qatar's 2022 exit form expected to continue", confidence:"High" },
  "Switzerland||Bosnia-Herzegovina": { h:2, a:0, r:"Swiss defensive solidity and tournament experience decisive", confidence:"High" },
  "Canada||Qatar": { h:3, a:0, r:"Canada need goals — Qatar have no answers for North American hosts", confidence:"High" },
  "Switzerland||Canada": { h:1, a:1, r:"Group decider — both cautious knowing a draw probably advances both", confidence:"Medium" },
  "Bosnia-Herzegovina||Qatar": { h:2, a:0, r:"Bosnia must win to have any chance — Qatar offer little resistance", confidence:"High" },

  // ── GROUP C ──────────────────────────────────────────────────────────────────
  "Brazil||Morocco": { h:2, a:1, r:"Vinicius Jr. and Rodrygo too dangerous even for Morocco's famous defensive block", confidence:"Medium" },
  "Haiti||Scotland": { h:0, a:2, r:"Scotland handle Haiti's debut comfortably — Robertson influential at left back", confidence:"High" },
  "Scotland||Morocco": { h:0, a:1, r:"Morocco's pace and organisation edges a limited Scotland attack", confidence:"Medium" },
  "Brazil||Haiti": { h:5, a:0, r:"Brazil score freely — Haiti's first World Cup offers no competitive resistance", confidence:"High" },
  "Scotland||Brazil": { h:0, a:3, r:"Brazil's attacking quality in a different class — Scotland set up defensively but outgunned", confidence:"High" },
  "Morocco||Haiti": { h:3, a:0, r:"Morocco secure second place comfortably against outclassed Haiti", confidence:"High" },

  // ── GROUP D ──────────────────────────────────────────────────────────────────
  "USA||Paraguay": { h:2, a:1, r:"USMNT strong at home — Pulisic and Reyna the difference on home soil", confidence:"High" },
  "Australia||Turkey": { h:1, a:1, r:"Australia's Socceroos always competitive but Turkey equally matched", confidence:"Low" },
  "USA||Australia": { h:2, a:1, r:"USA home advantage and depth edges a spirited Australia side", confidence:"Medium" },
  "Turkey||Paraguay": { h:2, a:1, r:"Turkey's Bundesliga quality sees off Paraguay in a competitive match", confidence:"Medium" },
  "Turkey||USA": { h:1, a:2, r:"USA edge it at home despite Turkey's resilience — crucial qualification match", confidence:"Medium" },
  "Paraguay||Australia": { h:1, a:1, r:"Neither side can afford to lose — cautious draw likely", confidence:"Low" },

  // ── GROUP E ──────────────────────────────────────────────────────────────────
  "Germany||Curacao": { h:5, a:0, r:"Germany make a statement after 2022 failure — Curacao hopelessly outmatched", confidence:"High" },
  "Ivory Coast||Ecuador": { h:1, a:1, r:"Ivory Coast's pace vs Ecuador's organisation — competitive and even", confidence:"Low" },
  "Germany||Ivory Coast": { h:2, a:1, r:"Germany's superior squad depth wins though Ivory Coast cause problems with pace", confidence:"Medium" },
  "Ecuador||Curacao": { h:4, a:0, r:"Ecuador need goals to compete with Germany on GD — Curacao ideal opponents", confidence:"High" },
  "Curacao||Ivory Coast": { h:0, a:3, r:"Ivory Coast quality and experience far too much for tournament debutants", confidence:"High" },
  "Ecuador||Germany": { h:0, a:2, r:"Germany secure top spot — Ecuador give it a go but outclassed in final third", confidence:"High" },

  // ── GROUP F ──────────────────────────────────────────────────────────────────
  "Netherlands||Japan": { h:2, a:1, r:"Netherlands edge it but Japan's 2022 giant-killing makes this nervy — de Jong injury concern", confidence:"Medium" },
  "Sweden||Tunisia": { h:2, a:0, r:"Alexander Isak's pace and quality decisive — Tunisia limited going forward", confidence:"High" },
  "Netherlands||Sweden": { h:2, a:1, r:"Gakpo vs Isak the key duel — Netherlands' superior depth decides it", confidence:"Medium" },
  "Tunisia||Japan": { h:0, a:2, r:"Japan's pressing and technical quality overwhelming for Tunisia's defensive setup", confidence:"High" },
  "Japan||Sweden": { h:1, a:2, r:"Sweden's aerial threat and Isak's movement gives Japan real problems", confidence:"Medium" },
  "Tunisia||Netherlands": { h:0, a:3, r:"Netherlands top the group — Tunisia have little to offer at this level", confidence:"High" },

  // ── GROUP G ──────────────────────────────────────────────────────────────────
  "Belgium||Egypt": { h:3, a:0, r:"De Bruyne and Lukaku too powerful — Belgium projected third highest group goals total", confidence:"High" },
  "Iran||New Zealand": { h:2, a:0, r:"Iran's tournament experience decisive against New Zealand's debut", confidence:"High" },
  "Belgium||Iran": { h:2, a:0, r:"Belgium's press and technical quality breaks Iran's defensive block", confidence:"High" },
  "New Zealand||Egypt": { h:0, a:2, r:"Salah makes the difference — Egypt overcome New Zealand despite star's age", confidence:"High" },
  "Egypt||Iran": { h:1, a:1, r:"Neither side can afford to lose — tactical and tense, draw most likely", confidence:"Low" },
  "New Zealand||Belgium": { h:0, a:4, r:"Belgium's 65% group win probability on show — New Zealand overwhelmed", confidence:"High" },

  // ── GROUP H ──────────────────────────────────────────────────────────────────
  "Spain||Cape Verde": { h:4, a:0, r:"Spain leads all 48 teams in projected goals — Yamal and Pedri give Cape Verde no chance", confidence:"High" },
  "Saudi Arabia||Uruguay": { h:0, a:2, r:"Uruguay's Nunez too powerful for Saudi defence despite their famous 2022 upset", confidence:"High" },
  "Spain||Saudi Arabia": { h:3, a:0, r:"Spain's possession game and pressing overwhelms Saudi Arabia's organised shape", confidence:"High" },
  "Uruguay||Cape Verde": { h:2, a:0, r:"Uruguay's South American quality and Nunez's power decisive", confidence:"High" },
  "Cape Verde||Saudi Arabia": { h:1, a:1, r:"Dead rubber for pride — neither team with much to play for", confidence:"Low" },
  "Uruguay||Spain": { h:1, a:2, r:"Group H decider — Spain's technical superiority edges Uruguay's physicality", confidence:"Medium" },

  // ── GROUP I ──────────────────────────────────────────────────────────────────
  "France||Senegal": { h:2, a:1, r:"Mbappe vs Mane the headline duel — France +500 tournament favourites have the depth", confidence:"High" },
  "Iraq||Norway": { h:0, a:3, r:"Haaland gets his warm-up — Iraq hopelessly outmatched against Norway's striker", confidence:"High" },
  "France||Iraq": { h:4, a:0, r:"France rotate but still win heavily — their second string is world class", confidence:"High" },
  "Norway||Senegal": { h:2, a:1, r:"Haaland's physicality vs Senegal's defenders — Norway's directness wins it", confidence:"Medium" },
  "Norway||France": { h:1, a:2, r:"Mbappe vs Haaland showdown — France's superior squad depth ultimately decisive", confidence:"Medium" },
  "Senegal||Iraq": { h:3, a:0, r:"Senegal quality shines in must-win match — Iraq have no answer", confidence:"High" },

  // ── GROUP J ──────────────────────────────────────────────────────────────────
  "Argentina||Algeria": { h:3, a:0, r:"Defending champions start strongly — Messi's final World Cup adds motivation", confidence:"High" },
  "Austria||Jordan": { h:3, a:0, r:"Austria's Bundesliga quality decisive against Jordan's first World Cup appearance", confidence:"High" },
  "Argentina||Austria": { h:2, a:1, r:"Argentina too good but Austria competitive — Alario a genuine threat", confidence:"High" },
  "Jordan||Algeria": { h:0, a:2, r:"Algeria's AFCON experience decisive — Jordan's debut limited by squad quality", confidence:"High" },
  "Algeria||Austria": { h:1, a:2, r:"Austria edge it — Algeria's form competitive but squad depth lacking", confidence:"Medium" },
  "Jordan||Argentina": { h:0, a:4, r:"Argentina win big to finish group — Messi and Alvarez share the goals", confidence:"High" },

  // ── GROUP K ──────────────────────────────────────────────────────────────────
  "Portugal||DR Congo": { h:3, a:0, r:"Bruno Fernandes and Bernardo Silva control midfield — DR Congo overwhelmed", confidence:"High" },
  "Uzbekistan||Colombia": { h:0, a:2, r:"James Rodriguez's class and Colombia's South American quality too much", confidence:"High" },
  "Portugal||Uzbekistan": { h:4, a:0, r:"Portugal run up a big score — Uzbekistan out of their depth at this level", confidence:"High" },
  "Colombia||DR Congo": { h:2, a:0, r:"Colombia's technical superiority and tactical organisation decisive", confidence:"High" },
  "Colombia||Portugal": { h:1, a:2, r:"Group K top match — Portugal's midfield quality edges a competitive Colombia", confidence:"Medium" },
  "DR Congo||Uzbekistan": { h:2, a:0, r:"DR Congo's pace and physicality decisive — both fighting for third-place points", confidence:"Medium" },

  // ── GROUP L ──────────────────────────────────────────────────────────────────
  "England||Croatia": { h:2, a:1, r:"Bellingham leads England's revenge for 2018 — stronger squad, same motivation", confidence:"High" },
  "Ghana||Panama": { h:2, a:0, r:"Ghana's Premier League talent too much for Panama's physical but limited squad", confidence:"High" },
  "England||Ghana": { h:3, a:0, r:"England's depth dominant — Saka and Bellingham the stars, Ghana limited", confidence:"High" },
  "Panama||Croatia": { h:0, a:2, r:"Modric still the orchestrator — Croatia's tournament experience decisive", confidence:"High" },
  "Panama||England": { h:0, a:4, r:"Echoes of England 6-1 Panama in 2018 — similar result expected with rotation", confidence:"High" },
  "Croatia||Ghana": { h:2, a:1, r:"Croatia's big-game experience decisive in tight group decider", confidence:"Medium" },
};

export default GROUP_AI_PREDICTIONS;
