// ─── AI QF PREDICTIONS ────────────────────────────────────────────────────────
// Generated by Claude — July 7, 2026
// Based on R16 performances

const QF_AI_PREDICTIONS = {

  // Jul 9 — Boston (Gillette Stadium)
  "France||Morocco": {
    h:2, a:1, confidence:"Medium",
    r:"2022 semi-final rematch — France's depth edges Morocco's resilience",
    insight:"A blockbuster rematch of the 2022 WC semi-final. Morocco dismantled Canada 3-0 in stunning fashion — Ounahi was exceptional. France edged Paraguay 1-0 in a tighter-than-expected game. Mbappé and Griezmann are the best attacking pair left in the tournament. But Morocco under Regragui have proved they can beat anyone on their day — their defensive block is the best remaining. France's squad depth wins out in the end, but Morocco will make them work.",
    key:"Mbappé's pace vs Morocco's organised defensive block",
  },
  "Morocco||France": {
    h:1, a:2, confidence:"Medium",
    r:"France's depth edges Morocco in a tight QF rematch",
    insight:"Morocco's defensive organisation will be tested by France's attacking quality.",
    key:"Mbappé's pace vs Morocco's defensive block",
  },

  // Jul 10 — Los Angeles (SoFi Stadium)
  "Spain||Belgium": {
    h:2, a:1, confidence:"Medium",
    r:"Spain's possession game edges Belgium — but De Bruyne can produce anything",
    insight:"Spain beat Portugal 1-0 in the Iberian derby with Mikel Merino's late goal. Belgium sensationally beat USA 4-1 — De Bruyne was unstoppable with 3 assists. This is the QF's most uncertain match. Spain's system is the best in the tournament but Belgium on form are terrifying. Pedri vs De Bruyne is the match-within-a-match. Spain's collective system should prevail but Belgium's individual quality makes this genuinely 50-50.",
    key:"Pedri vs De Bruyne — the battle that decides this QF",
  },
  "Belgium||Spain": {
    h:1, a:2, confidence:"Medium",
    r:"Spain's system edges Belgium despite De Bruyne's brilliance",
    insight:"De Bruyne had the game of his career against USA but Spain's collective is the strongest remaining.",
    key:"Spain's high press disrupting Belgium's build-up",
  },

  // Jul 11 — Miami (Hard Rock Stadium)
  "Norway||England": {
    h:1, a:2, confidence:"Medium",
    r:"Haaland vs Bellingham — England's balance edges Norway's Haaland-dependence",
    insight:"Norway's stunning 2-1 win over Brazil — Haaland with 2 goals — is one of the tournament's great upsets. England beat Mexico 3-2 in a thriller at the Azteca. Haaland has 8 goals and is the tournament's top scorer. But England are more balanced — Bellingham, Saka, Foden, Watkins all contributing. Norway's reliance on Haaland is the key vulnerability. England's defence, marshalled by Stones, has the tools to limit him.",
    key:"Can England's defence neutralise Haaland's movement?",
  },
  "England||Norway": {
    h:2, a:1, confidence:"Medium",
    r:"England's balance and depth edges Haaland's Norway",
    insight:"Bellingham and Saka create from everywhere. Norway are one-dimensional without Haaland.",
    key:"England's defensive organisation limiting Haaland",
  },

  // Jul 11 — Kansas City (Arrowhead Stadium)
  "Argentina||Switzerland": {
    h:2, a:0, confidence:"High",
    r:"Messi's Argentina are on a different level — Switzerland will be outclassed",
    insight:"Argentina's comeback from 2-0 down to beat Egypt 3-2 was the tournament's defining moment — Messi with 8 goals is the Golden Boot leader. Switzerland beat Colombia 4-3 on penalties in a dull 0-0. Argentina have too much quality — Messi, Álvarez, Lautaro, Di María, Enzo Fernández. Switzerland's organisation will delay but not stop Argentina's inevitable progression.",
    key:"Messi's tournament-defining form continuing into the semis",
  },
  "Switzerland||Argentina": {
    h:0, a:2, confidence:"High",
    r:"Argentina are overwhelming favourites",
    insight:"Messi is on a historic run. Switzerland's 0-0 vs Colombia showed their defensive limitations.",
    key:"Argentina's attacking quality overwhelming Switzerland",
  },
};

export default QF_AI_PREDICTIONS;
