// ─── AI R16 PREDICTIONS ───────────────────────────────────────────────────────
// Generated by Claude — July 4, 2026

const R16_AI_PREDICTIONS = {
  "Canada||Morocco": {
    h:1, a:2, confidence:"Medium",
    r:"Morocco's knockout pedigree and defensive organisation edges Canada",
    insight:"Canada made history beating South Africa but face a different level. Morocco beat Netherlands on penalties after 1-1, showing their defensive organisation and set-piece threat. Sofyan Amrabat is playing the tournament of his career. Canada's Jonathan David is the danger — but Morocco's compactness will frustrate. Morocco edge it in extra time.",
    key:"Sofyan Amrabat neutralising Canada's midfield creativity",
  },
  "Morocco||Canada": {
    h:2, a:1, confidence:"Medium",
    r:"Morocco's knockout pedigree and defensive organisation edges Canada",
    insight:"Canada made history beating South Africa but face a different level. Morocco beat Netherlands on penalties after 1-1, showing their defensive organisation and set-piece threat. Sofyan Amrabat is playing the tournament of his career. Canada's Jonathan David is the danger — but Morocco's compactness will frustrate. Morocco edge it.",
    key:"Sofyan Amrabat neutralising Canada's midfield creativity",
  },
  "Paraguay||France": {
    h:0, a:3, confidence:"High",
    r:"France are the tournament favourites — Paraguay won on penalties and have limited attacking quality",
    insight:"France destroyed Sweden 3-0 with Mbappé scoring twice. Paraguay needed penalties to beat Germany and will face an enormous step up in quality. Griezmann and Mbappé together are unplayable when France have the ball. Paraguay's defensive resilience earned them this result but they simply don't have the attacking tools to threaten Les Bleus.",
    key:"Mbappé's pace on the break will destroy Paraguay",
  },
  "France||Paraguay": {
    h:3, a:0, confidence:"High",
    r:"France are the tournament favourites — Paraguay won on penalties and have limited attacking quality",
    insight:"France destroyed Sweden 3-0 with Mbappé scoring twice. Paraguay needed penalties to beat Germany.",
    key:"Mbappé's pace on the break",
  },
  "Brazil||Norway": {
    h:2, a:1, confidence:"Medium",
    r:"Brazil's flair vs Haaland's threat — Brazil have too much quality but Norway won't be easy",
    insight:"Brazil breezed past Japan 2-1 with Vinícius Jr dominant. Norway edged Ivory Coast 2-1 with Haaland scoring his 5th of the tournament. This is the most dangerous R16 match for Brazil. Haaland will cause chaos against any defence. But Brazil's attacking depth — Rodrygo, Raphinha, Endrick off the bench — should be decisive.",
    key:"Can Brazil's defence handle Haaland's direct play?",
  },
  "Norway||Brazil": {
    h:1, a:2, confidence:"Medium",
    r:"Brazil's flair vs Haaland's threat — Brazil have too much quality",
    insight:"Haaland is the best striker in the tournament but Brazil's defensive depth and attacking quality is overwhelming.",
    key:"Vinícius Jr's pace on the counter",
  },
  "Mexico||England": {
    h:1, a:2, confidence:"Medium",
    r:"England's quality edges Mexico in an electric Azteca atmosphere",
    insight:"Mexico won all three group games and beat Ecuador 2-0 — perfect form. England beat DR Congo 2-1. The Azteca crowd will be extraordinary. Bellingham is the danger. England's defensive organisation and quality at the top — Saka, Foden, Bellingham — is decisive.",
    key:"Jude Bellingham arriving late into the box from midfield",
  },
  "England||Mexico": {
    h:2, a:1, confidence:"Medium",
    r:"England's quality edges Mexico despite the Azteca atmosphere",
    insight:"Bellingham and Saka are the difference-makers.",
    key:"England's quality in the final third",
  },
  "Portugal||Spain": {
    h:1, a:2, confidence:"Medium",
    r:"The Iberian derby — Spain's possession game outclasses Portugal",
    insight:"The marquee R16 tie. Ronaldo at 41 scored against Croatia. Spain have been flawless — 3-0 vs Austria. Pedri-Gavi-Rodri vs Bruno Fernandes is fascinating. Spain's pressing suffocates even the best teams. Portugal can hurt on the break but Spain control possession too well.",
    key:"Spain's midfield trio winning the battle in the centre",
  },
  "Spain||Portugal": {
    h:2, a:1, confidence:"Medium",
    r:"Spain's possession game outclasses Portugal's aging side",
    insight:"Spain's pressing and midfield quality is decisive.",
    key:"Pedri dictating play in the final third",
  },
  "USA||Belgium": {
    h:2, a:1, confidence:"Medium",
    r:"Home crowd + Pulisic on fire = USA's best ever World Cup result",
    insight:"USA beat Bosnia 2-0 with Pulisic and Balogun brilliant. Belgium staged a comeback to beat Senegal 3-2. Lumen Field will be an incredible atmosphere. USA's high press perfectly suits this game. Pulisic is playing the best football of his career.",
    key:"Christian Pulisic exploiting space behind Belgium's high line",
  },
  "Belgium||USA": {
    h:1, a:2, confidence:"Medium",
    r:"USA's home advantage and form edges Belgium",
    insight:"De Bruyne can still produce but USA's press and home crowd will be overwhelming.",
    key:"USA's high press disrupting De Bruyne's rhythm",
  },
  "Argentina||Egypt": {
    h:3, a:0, confidence:"High",
    r:"Argentina will be far too strong for Egypt despite their Cabo Verde scare",
    insight:"Argentina's 3-2 win over Cabo Verde in extra time was more difficult than expected. Egypt beat Australia on penalties. Salah can produce a moment of genius but Argentina's depth — Álvarez, Lautaro, Di María — is simply on another level.",
    key:"Lionel Messi creating one final knockout-stage magic moment",
  },
  "Egypt||Argentina": {
    h:0, a:3, confidence:"High",
    r:"Argentina are simply too strong",
    insight:"Egypt's defensive organisation will delay but not prevent Argentina. Messi and Álvarez are in top form.",
    key:"Messi's creativity unlocking Egypt's compact defence",
  },
  "Switzerland||Colombia": {
    h:1, a:2, confidence:"Medium",
    r:"James Rodríguez's tournament has been magnificent — Colombia edge Switzerland",
    insight:"Switzerland beat Algeria 2-0. Colombia beat Ghana 1-0 with James pulling all the strings. At 34, James is having a career-defining World Cup. Colombia's counter-attacking threat suits knockout football.",
    key:"James Rodríguez dictating the pace from deep",
  },
  "Colombia||Switzerland": {
    h:2, a:1, confidence:"Medium",
    r:"Colombia's creativity edges Switzerland's organisation",
    insight:"James Rodríguez is the best player in the tournament right now.",
    key:"James Rodríguez's vision and passing range",
  },
};

export default R16_AI_PREDICTIONS;
