// ─── AI R32 PREDICTIONS ───────────────────────────────────────────────────────
// Generated by Claude Sonnet 4.6 — June 2026
// Fields: h (home goals), a (away goals), r (short reason),
//         insight (2-3 sentence analysis), key (key factor), confidence

const R32_AI_PREDICTIONS = {

  // ── Jun 28 ────────────────────────────────────────────────────────────────
  "South Africa||Canada": {
    h:1, a:2, confidence:"Medium",
    r:"Canada's physical press too much for South Africa's limited attacking quality",
    insight:"Canada finished 2nd in Group B behind Switzerland but showed real threat through Jonathan David and Alphonso Davies. South Africa shocked Korea in the group stage but lack knockout-round pedigree. Canada's 4-3-3 press should suffocate a South African side with low possession stats.",
    key:"Jonathan David's movement against South Africa's high line",
  },
  "Brazil||Japan": {
    h:3, a:0, confidence:"High",
    r:"Brazil's squad depth and individual quality too much for Japan",
    insight:"Brazil won Group C comfortably, with Vinícius Jr and Rodrygo combining for 5 goals. Japan beat Sweden 1-1 to qualify but their defensive shape will buckle under relentless Brazilian pressure. Carlo Ancelotti's side have looked the best team of the tournament so far.",
    key:"Vinícius Jr's pace against Japan's full-backs",
  },
  "Germany||Paraguay": {
    h:3, a:0, confidence:"High",
    r:"Germany's quality enormous vs CONMEBOL's weakest R32 side",
    insight:"Germany topped Group E with 7 points, conceding just 1 goal. Paraguay squeezed through as 3rd place with 4 points and a -1 goal difference. Nagelsmann's side have depth at every position — this is the most lopsided R32 matchup on paper.",
    key:"Germany's pressing intensity in the first 20 minutes",
  },
  "Netherlands||Morocco": {
    h:2, a:1, confidence:"Medium",
    r:"Netherlands edge a tight tactical battle — Morocco can hurt them",
    insight:"This is the pick of the R32. Morocco beat Brazil in the 2022 QF and have stunning organisation under Regragui. But the Dutch have Cody Gakpo and Memphis Depay in top form. Three Dutch-born players in Morocco's squad adds intrigue. Expect a cagey first half then Netherlands pull away.",
    key:"Sofyan Amrabat's ability to cut off the Dutch midfield",
  },

  // ── Jun 30 ────────────────────────────────────────────────────────────────
  "Ivory Coast||Norway": {
    h:1, a:2, confidence:"Medium",
    r:"Haaland and Ødegaard too clinical for Ivory Coast's aging squad",
    insight:"Norway rotated heavily against France but Haaland returns refreshed with 4 goals in 2 games. Ivory Coast qualified as runners-up but struggled in their final group game. Yan Diomandé is electric but Norway's counterattacking speed suits knockout football perfectly.",
    key:"Erling Haaland — any service and he scores",
  },
  "France||Sweden": {
    h:3, a:1, confidence:"High",
    r:"France are tournament favourites and Sweden have a negative goal difference",
    insight:"France won Group I with all 9 points and +8 goal difference. Sweden scraped through as a third-place team with 4 points. Mbappé, Griezmann and Camavinga are all in brilliant form. Sweden's Alexander Isak is the only genuine threat — but France's backline is the best in the tournament.",
    key:"Mbappé's directness against Sweden's defensive shape",
  },
  "Mexico||Ecuador": {
    h:2, a:1, confidence:"Medium",
    r:"Mexico's home support advantage in Mexico City decisive",
    insight:"Mexico topped Group A with 9 points — flawless group stage. Ecuador qualified as 3rd place through a dramatic final-group-game win. The Azteca crowd will be the 12th man for Mexico, but Ecuador have Moisés Caicedo pulling strings in midfield. Expect Mexico to win, but Ecuador to make them work.",
    key:"Mexico's crowd advantage at Estadio Azteca",
  },

  // ── Jul 1 ─────────────────────────────────────────────────────────────────
  "England||DR Congo": {
    h:3, a:0, confidence:"High",
    r:"England too powerful and organised for DR Congo's limited squad",
    insight:"England topped Group L with 7 points and look fluid under new manager. DR Congo are a remarkable story — qualifying as 3rd place — but they face a different level now. Bellingham, Saka and Foden have all clicked. This should be comfortable for England.",
    key:"Bellingham's ability to arrive late into the box",
  },
  "Belgium||Senegal": {
    h:2, a:1, confidence:"Medium",
    r:"Belgium's De Bruyne-led golden generation make one last run",
    insight:"Belgium were dominant in their group, thrashing New Zealand 5-1. Senegal qualified as a surprise 3rd-place finisher with Sadio Mané still threatening. But De Bruyne, Lukaku and Trossard give Belgium an edge in creativity. This is Belgium's last realistic chance at a major trophy before the generation turns over.",
    key:"Kevin De Bruyne — his final World Cup knockout run",
  },
  "USA||Bosnia-Herzegovina": {
    h:2, a:1, confidence:"Medium",
    r:"USA's home crowd and momentum make them slight favourites",
    insight:"USA won Group D and have genuine momentum — Christian Pulisic is the best player of the group stage among the co-hosts. Bosnia qualified as 3rd place and have Edin Džeko as their veteran threat. Levi's Stadium will be a cauldron. USA in extra time is not off the table.",
    key:"Christian Pulisic's creativity in tight spaces",
  },

  // ── Jul 2 ─────────────────────────────────────────────────────────────────
  "Spain||Austria": {
    h:2, a:0, confidence:"High",
    r:"Spain's possession game should neutralise Austria completely",
    insight:"Spain have been unconvincing but effective — 1-0 wins are their mode. Austria qualified from Group J runners-up but have looked pedestrian. Spain's Pedri-Gavi-Rodri midfield is the best in the tournament and Austria will have very little of the ball. Expect a controlled Spanish win.",
    key:"Rodri controlling the tempo from deep",
  },
  "Portugal||Croatia": {
    h:2, a:1, confidence:"Medium",
    r:"Portugal's attacking quality edges a classic Ronaldo-Modric reunion",
    insight:"Remarkable that at 41 and 39 years old, Ronaldo and Modric are still leading their countries in a World Cup knockout game. Portugal's supporting cast — Bruno Fernandes, Bernardo Silva, Rafael Leão — gives them the edge. Croatia are masters of deep blocks and counterattacks but Portugal have the firepower.",
    key:"Bruno Fernandes creating from the 10 position",
  },
  "Switzerland||Algeria": {
    h:2, a:1, confidence:"Medium",
    r:"Switzerland's organisation and Xhaka's leadership see them through",
    insight:"Switzerland topped Group B and have been solid if unspectacular. Algeria qualified from Group J and have real threat through Riyad Mahrez. Granit Xhaka is Switzerland's heartbeat and at 32 he's at his peak. Algeria will threaten on the counter but Switzerland's tactical discipline should be enough.",
    key:"Granit Xhaka's reading of the game",
  },

  // ── Jul 3 ─────────────────────────────────────────────────────────────────
  "Australia||Egypt": {
    h:1, a:1, confidence:"Low",
    r:"Complete toss-up — both sides qualified as runners-up with modest records",
    insight:"Australia qualified from Group D runners-up but struggled against the USA. Egypt was runner-up in Group G — a massive achievement. Mohamed Salah is Egypt's match-winner but at 33 his legs aren't quite what they were. The Socceroos have heart and organisation. Penalties wouldn't surprise.",
    key:"Mohamed Salah — can he impose himself one last time?",
  },
  "Argentina||Cape Verde": {
    h:4, a:0, confidence:"Very High",
    r:"Argentina vs Cape Verde is the most lopsided R32 matchup imaginable",
    insight:"Cape Verde are the smallest nation ever to reach a World Cup knockout stage — an incredible achievement. But Lionel Messi, Julián Álvarez and Lautaro Martínez against Cape Verde's defence is barely fair. Argentina need to win comfortably and then recover for a tough R16. Expect Messi to enjoy himself.",
    key:"Messi enjoying his last R32 appearance",
  },
  "Colombia||Ghana": {
    h:2, a:0, confidence:"Medium",
    r:"Colombia's technical quality and James Rodríguez too much for Ghana",
    insight:"Colombia topped Group K and James Rodríguez has been one of the players of the tournament at 34. Ghana qualified as 3rd place from Group L after a surprise run. But Colombia's pressing and technical level are a significant step up. Jordan Ayew and Mohammed Kudus are Ghana's threats but Colombia's compactness is impressive.",
    key:"James Rodríguez dictating play in Colombia's midfield",
  },
};

export default R32_AI_PREDICTIONS;
